# Use official Python base
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy only necessary files
COPY requirements.txt .
COPY run_pipeline.py .
COPY app/ ./app

# Install dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Set default command to run the pipeline on container start
CMD ["python", "run_pipeline.py"]
